#!/usr/bin/env node
/**
 * strip-shopify.mjs
 *
 * Removes the Shopify e-commerce integration from this boilerplate. Run once,
 * when starting a project that does not need e-commerce:
 *
 *     pnpm strip:shopify
 *
 * The script is deliberately dumb. It carries no list of Shopify files or code
 * — it only understands two markers, which live next to the code they guard:
 *
 *     // #shopify-file                     (in the first 3 lines) → delete the whole file
 *     // #region shopify … // #endregion shopify → delete the enclosed lines
 *
 * Comment syntax is irrelevant; only the token is matched. So the same markers
 * work in .ts, .tsx, .astro, .svelte, .md, .jsonc, .env files, and inside GROQ
 * template literals.
 *
 * Adding new Shopify code means adding markers, not editing this script.
 *
 * Flags:
 *   --dry-run   report what would change, write nothing
 *   --yes       skip the confirmation prompt
 */

import { execSync } from "node:child_process";
import { createInterface } from "node:readline/promises";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const FILE_MARKER = "#shopify-file";
const REGION_START = "#region shopify";
const REGION_END = "#endregion shopify";

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  // Agent tooling, not shipped project source. The setup skill detects whether
  // Shopify has already been stripped by checking the root package.json scripts,
  // so it stays correct in both states without being rewritten here.
  ".claude",
  "dist",
  "build",
  ".astro",
  ".sanity",
  ".wrangler",
  ".vercel",
  ".next",
  "coverage",
]);

// Binary / lockfile extensions we never rewrite. Lockfiles legitimately contain
// the string "shopify" in package metadata and are regenerated by `pnpm install`.
const SKIP_FILES = new Set(["pnpm-lock.yaml", "package-lock.json", "yarn.lock"]);

// Paths (relative to ROOT) the script must never read as input. This file
// documents the marker syntax, so it necessarily contains the marker tokens.
const SKIP_PATHS = new Set(["scripts/strip-shopify.mjs"]);

// Local, gitignored env files. These hold real credentials and are the
// developer's to manage — the summary reminds them to clear the Shopify vars.
const isEnvFile = (name) => name === ".env" || name.startsWith(".env.");
const SKIP_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".ico",
  ".woff", ".woff2", ".ttf", ".otf", ".eot",
  ".mp4", ".webm", ".pdf", ".zip",
]);

const args = new Set(process.argv.slice(2));
const DRY_RUN = args.has("--dry-run");
const ASSUME_YES = args.has("--yes") || args.has("-y");

/** Recursively collect candidate files. */
const walk = (dir, out = []) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(path.join(dir, entry.name), out);
    } else if (entry.isFile()) {
      if (SKIP_FILES.has(entry.name)) continue;
      if (SKIP_EXT.has(path.extname(entry.name).toLowerCase())) continue;
      if (isEnvFile(entry.name) && entry.name !== ".env.example") continue;
      const full = path.join(dir, entry.name);
      if (SKIP_PATHS.has(path.relative(ROOT, full))) continue;
      out.push(full);
    }
  }
  return out;
};

/**
 * Remove #region shopify … #endregion shopify blocks.
 * Throws on an unterminated region so a broken marker fails the run loudly
 * rather than silently deleting the rest of a file.
 */
const stripRegions = (text, relPath) => {
  const lines = text.split("\n");
  const kept = [];
  let depth = 0;
  let removed = 0;
  let openedAt = 0;

  lines.forEach((line, i) => {
    if (line.includes(REGION_START)) {
      if (depth === 0) openedAt = i + 1;
      depth += 1;
      removed += 1;
      return;
    }
    if (line.includes(REGION_END)) {
      if (depth === 0) {
        throw new Error(`${relPath}:${i + 1} — #endregion shopify without a matching #region`);
      }
      depth -= 1;
      removed += 1;
      return;
    }
    if (depth > 0) {
      removed += 1;
      return;
    }
    kept.push(line);
  });

  if (depth > 0) {
    throw new Error(`${relPath}:${openedAt} — #region shopify was never closed`);
  }

  return { text: kept.join("\n"), removed };
};

/** Remove directories that the file deletions left empty, deepest-first. */
const pruneEmptyDirs = (dir) => {
  let pruned = [];
  if (!fs.existsSync(dir)) return pruned;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory() && !SKIP_DIRS.has(entry.name)) {
      pruned = pruned.concat(pruneEmptyDirs(path.join(dir, entry.name)));
    }
  }
  if (fs.readdirSync(dir).length === 0 && dir !== ROOT) {
    if (!DRY_RUN) fs.rmdirSync(dir);
    pruned.push(path.relative(ROOT, dir));
  }
  return pruned;
};

const rel = (p) => path.relative(ROOT, p);

// ---------------------------------------------------------------------------

const files = walk(ROOT);

const toDelete = [];
const toRewrite = [];

for (const file of files) {
  let text;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch {
    continue; // unreadable / binary
  }

  if (text.split("\n", 3).join("\n").includes(FILE_MARKER)) {
    toDelete.push(file);
    continue;
  }

  if (text.includes(REGION_START) || text.includes(REGION_END)) {
    const { text: stripped, removed } = stripRegions(text, rel(file));
    toRewrite.push({ file, text: stripped, removed });
  }
}

if (toDelete.length === 0 && toRewrite.length === 0) {
  console.log("No Shopify markers found — nothing to strip.");
  process.exit(0);
}

console.log(`\nFiles to delete (${toDelete.length}):`);
for (const f of toDelete) console.log(`  - ${rel(f)}`);

console.log(`\nFiles to edit (${toRewrite.length}):`);
for (const { file, removed } of toRewrite) {
  console.log(`  ~ ${rel(file)} (${removed} lines)`);
}

if (DRY_RUN) {
  console.log("\n--dry-run: no changes written.");
  process.exit(0);
}

if (!ASSUME_YES) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const answer = await rl.question("\nProceed? This rewrites files in place. [y/N] ");
  rl.close();
  if (!/^y(es)?$/i.test(answer.trim())) {
    console.log("Aborted.");
    process.exit(1);
  }
}

for (const file of toDelete) fs.unlinkSync(file);
for (const { file, text } of toRewrite) fs.writeFileSync(file, text);

const prunedDirs = pruneEmptyDirs(ROOT);
if (prunedDirs.length) {
  console.log(`\nRemoved empty directories:`);
  for (const d of prunedDirs) console.log(`  - ${d}`);
}

// ---------------------------------------------------------------------------
// Self-cleanup: once Shopify is gone this script and its npm aliases are dead
// weight referencing something that no longer exists. Must happen before the
// residue assertion below, which would otherwise flag the script's own aliases.

const selfPath = fileURLToPath(import.meta.url);
const rootPkgPath = path.join(ROOT, "package.json");
if (fs.existsSync(rootPkgPath)) {
  const pkg = JSON.parse(fs.readFileSync(rootPkgPath, "utf8"));
  delete pkg.scripts?.["strip:shopify"];
  delete pkg.scripts?.["strip:shopify:dry"];
  if (pkg.scripts && Object.keys(pkg.scripts).length === 0) delete pkg.scripts;
  fs.writeFileSync(rootPkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}
fs.unlinkSync(selfPath);
const scriptsDir = path.dirname(selfPath);
if (fs.readdirSync(scriptsDir).length === 0) fs.rmdirSync(scriptsDir);

// ---------------------------------------------------------------------------
// Assert clean. This is the property that makes the script trustworthy: if any
// Shopify reference survives, we want a loud failure, not a quiet half-strip.

const residue = [];
for (const file of walk(ROOT)) {
  let text;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch {
    continue;
  }
  text.split("\n").forEach((line, i) => {
    if (/shopify/i.test(line)) residue.push(`${rel(file)}:${i + 1}: ${line.trim()}`);
  });
}

if (residue.length) {
  console.error(`\n✗ ${residue.length} Shopify reference(s) survived the strip:\n`);
  for (const r of residue) console.error(`    ${r}`);
  console.error(
    "\nThese need a marker (or an entry in SKIP_PATHS). Files have already been\n" +
      "modified — use `git checkout .` to undo and re-run after adding markers.\n"
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------

console.log("\nReinstalling dependencies and formatting…");
for (const pkg of ["astro", "sanity"]) {
  const cwd = path.join(ROOT, pkg);
  const pkgJson = path.join(cwd, "package.json");
  if (!fs.existsSync(pkgJson)) continue;

  const run = (cmd, label) => {
    try {
      execSync(cmd, { cwd, stdio: "inherit" });
    } catch {
      console.warn(`  ! ${label} failed in ${pkg}/ — run it manually`);
    }
  };

  run("pnpm install", "install");

  // Not every sub-project defines a format script.
  const { scripts = {} } = JSON.parse(fs.readFileSync(pkgJson, "utf8"));
  if (scripts.format) run("pnpm format", "format");
}

console.log(`
✓ Shopify integration removed.
  ${toDelete.length} files deleted, ${toRewrite.length} files edited.
  This script has removed itself — the strip is one-way.

Next steps:
  1. Remove the Shopify vars from astro/.env (PUBLIC_SHOPIFY_*).
  2. Remove SANITY_STUDIO_SHOPIFY_STORE_ID from sanity/.env if set.
  3. Verify:  cd astro && pnpm build     (and: pnpm build:preview)
              cd sanity && pnpm build
  4. Commit.
`);
